### ISSUE TITLE
Peer to peer code review by team 125 The Elmos

### ISSUE THREAD

**Issue by ershadul1** [rloterh/NewsWeekClone#1]
There is some room for improvement in the project.

- Add a dot to image src. i.e. src="./image/filename.png" . This will solve all the issues with image processing.

- Open a pull request at the beginning of your work in the project. This will help you to reduce your time fixing linter errors.

- Order the top story section at the top of the mobile view.

- Use builtin bootstrap classes wherever you can in this project.

- Use links for clickable elements. e.g. images, titles.

**Comment by descholar-ceo** [comment]
This is cool, you have done a good job so far @ershadul1 && @rloterh, keep up the good job!
